Reconstruction quantification and dCrawler Py port
mleiwe/QDyeFinder pull request #9
Opened 2024-02-19 09:35 UTC by Elsword016

quantify swc reconstructions between Imaris tracing and qDyefinder.
Also initial implementation of dCrawler's python version

2024-02-20 02:45 UTC, mleiwe requested changes
Hi Bis, a few changes and suggestions here and there. Let me know if these are ok

2024-02-20 02:45 UTC, mleiwe commented on dCrawler_python/Readme.md
> +Still in the testing phase, wrote a general implementation of dCrawler, haven't tested with data, nor efficient currently. I think can be good starting point
Perhaps you should fork the dCrawler repository instead and put it there? dCrawler has scope beyond tracing so I want to keep the two repos separate.

2024-02-20 02:45 UTC, mleiwe commented on dCrawler_python/dCrawler_py.ipynb
Perhaps structuring it like a class in the sklearn format would be better in the end. Am happy if you want to practice using a notebook to check codes etc. But Spyder might be easier for that

2024-02-20 02:45 UTC, mleiwe commented on quantify_reconstructions/readme.md
Need a requirements .txt as well

2024-02-20 02:45 UTC, mleiwe commented on quantify_reconstructions/swc_analyze.ipynb
General comments.
1. Need to fix spellings, e.g. last cell ("Ground truth" not "grouth")
2. Q_dye autotrace is incorrect. It is not auto-traced. I just used the manual traces. 
i. The reviewer didn't ask for that comparison I believe. 
ii. However, if they did I suggest you ask Fujimoto-san or remote view yourself in to do the autotracing in Neurolucida360 for a fair comparison. 
4. Final presentation wise. A few comments
i.  For your penultimate plot, for the intersect and the union I suggest not having a white background. Keep it consistent with the two images on the left. (Perhaps grayscale is fine?). Oranges is not consistent with either of the colours
ii. To be honest I think the last image encapsulates both the Intersect and the Union in a single image and so is better. Could you sort it so that the ground truth is in green, the imaris in purple, this way the overlay should be white.
iii. For the final figure, I'd ideally like three panels (ground truth:left, imaris:middle, overlay:right). NB be careful about the scaling if the neurites look too thin I suggest downscaling the images so you can see the neurites (or dilate the neurites either works - as long as the dilation and/or downsampling is done after the IoU calculation).
iv. Would you be able to find the same neuron and isolate it in both Imaris and my manual tracing? Just as a close up example I think it would help.

2024-05-16 07:29 UTC, closed without merging

2024-05-16 07:29 UTC, Elsword016 commented
New PR needed, dismiss this